import type { DirectoryVocabulary } from '@pan/shared-types';

/**
 * The words the crawler uses to recognize a directory, a shared inbox and an
 * organizational label.
 *
 * Composable for the same reason the title rules are: "faculty" means a
 * directory in one vertical and nothing in another, and the adapters must not
 * have to know which vertical they are looking at. Sector packages contribute
 * their own terms and the composed vocabulary reaches adapters through
 * `AdapterContext`.
 */
export type { DirectoryVocabulary };

export const BASE_DIRECTORY_VOCABULARY: DirectoryVocabulary = {
  headingTerms: [
    'staff',
    'employee',
    'employees',
    'personnel',
    'directory',
    'our team',
    'team',
    'leadership',
    'administration',
    'officials',
    'elected officials',
    'contacts',
    'contact us',
    'departments',
    'offices',
    'divisions',
    'who we are',
  ],
  urlHints: [
    { pattern: '/(staff|employee)s?-directory(/|$)', weight: 1.0 },
    { pattern: '/(staff|employees?|personnel|officials)(/|$)', weight: 0.8 },
    { pattern: '/directory(/|$)', weight: 0.75 },
    { pattern: '/(our-)?(team|people)(/|$)', weight: 0.6 },
    { pattern: '/(administration|admin-team|leadership|executive-team)(/|$)', weight: 0.55 },
    { pattern: '/(elected-officials|officials|commissioners|council)(/|$)', weight: 0.55 },
    { pattern: '/(offices?|divisions?|bureaus?)(/|$)', weight: 0.4 },
    { pattern: '/contact-us?(/|$)', weight: 0.35 },
    { pattern: '/departments?(/|$)', weight: 0.3 },
  ],
  sharedInboxLocalParts: [
    'info',
    'information',
    'office',
    'frontoffice',
    'front-office',
    'mainoffice',
    'contact',
    'contactus',
    'webmaster',
    'web',
    'admin',
    'administrator',
    'help',
    'helpdesk',
    'support',
    'service',
    'services',
    'hello',
    'inquiries',
    'enquiries',
    'general',
    'mail',
    'email',
    'noreply',
    'no-reply',
    'donotreply',
    'postmaster',
    'abuse',
    'privacy',
    'legal',
    'compliance',
    'security',
    'hr',
    'humanresources',
    'jobs',
    'careers',
    'employment',
    'recruiting',
    'payroll',
    'benefits',
    'accounting',
    'accountspayable',
    'ap',
    'ar',
    'billing',
    'finance',
    'business',
    'purchasing',
    'procurement',
    'contracts',
    'clerk',
    'records',
    'permits',
    'licensing',
    'planning',
    'zoning',
    'inspections',
    'publicworks',
    'utilities',
    'water',
    'sewer',
    'sanitation',
    'streets',
    'police',
    'fire',
    'dispatch',
    'emergency',
    'safety',
    'health',
    'clinic',
    'nurse',
    'socialservices',
    'parks',
    'recreation',
    'library',
    'elections',
    'voter',
    'assessor',
    'treasurer',
    'tax',
    'news',
    'press',
    'media',
    'communications',
    'pio',
    'technology',
    'it',
    'ithelp',
    'techsupport',
    'maintenance',
    'facilities',
    'transportation',
    'transit',
    'fleet',
    'board',
    'council',
    'commission',
    'mayor',
    'cityhall',
    'townhall',
    'foia',
    'publicrecords',
    'ombudsman',
  ],
  sharedInboxPrefixes: [
    'info',
    'office',
    'contact',
    'help',
    'support',
    'admin',
    'noreply',
    'no-reply',
    'webmaster',
    'hr',
    'jobs',
    'careers',
    'library',
    'clerk',
    'permits',
    'records',
  ],
  organizationLabelWords: [
    'front',
    'main',
    'general',
    'central',
    'office',
    'offices',
    'department',
    'dept',
    'division',
    'bureau',
    'agency',
    'commission',
    'authority',
    'board',
    'committee',
    'council',
    'team',
    'staff',
    'reception',
    'desk',
    'line',
    'info',
    'information',
    'administration',
    'headquarters',
    'hq',
    'branch',
    'unit',
    'section',
    'district',
    'hall',
    'center',
    'centre',
    'clerk',
    'records',
    'permits',
    'licensing',
    'planning',
    'zoning',
    'police',
    'fire',
    'dispatch',
    'emergency',
    'safety',
    'security',
    'health',
    'clinic',
    'library',
    'parks',
    'recreation',
    'maintenance',
    'facilities',
    'technology',
    'transportation',
    'transit',
    'utilities',
    'water',
    'sewer',
    'sanitation',
    'streets',
    'elections',
    'treasurer',
    'assessor',
    'attendance',
    'registrar',
    'nurse',
  ],
  titleIndicatorTerms: [
    'director',
    'deputy',
    'assistant',
    'associate',
    'manager',
    'supervisor',
    'coordinator',
    'specialist',
    'analyst',
    'technician',
    'officer',
    'chief',
    'administrator',
    'clerk',
    'secretary',
    'assistant',
    'aide',
    'inspector',
    'engineer',
    'planner',
    'attorney',
    'counsel',
    'auditor',
    'accountant',
    'operator',
    'driver',
    'custodian',
    'mechanic',
    'nurse',
    'librarian',
    'commissioner',
    'mayor',
    'sheriff',
    'marshal',
    'captain',
    'sergeant',
    'lieutenant',
    'firefighter',
    'paramedic',
    'dispatcher',
    'planner',
    'president',
    'chairman',
    'chairwoman',
    'treasurer',
    'assessor',
    'registrar',
    'representative',
    'liaison',
    'ombudsman',
    'warden',
  ],
  organizationFieldAliases: [
    'organization',
    'organization_name',
    'organizationname',
    'agency',
    'agency_name',
    'bureau',
    'office',
    'office_name',
    'division',
    'department_name',
    'site',
    'location',
    'building',
    'facility',
    'jurisdiction',
  ],
  organizationNameSuffixes: [
    'department',
    'dept',
    'division',
    'bureau',
    'office',
    'agency',
    'commission',
    'authority',
    'board',
    'council',
    'district',
    'administration',
    'service',
    'services',
    'government',
    'county',
    'city of',
    'town of',
    'village of',
  ],
};

/** Merge sector contributions onto the base, de-duplicating every list. */
export function composeVocabulary(
  base: DirectoryVocabulary,
  contributions: readonly Partial<DirectoryVocabulary>[],
): DirectoryVocabulary {
  const merged: DirectoryVocabulary = {
    headingTerms: [...base.headingTerms],
    urlHints: [...base.urlHints],
    sharedInboxLocalParts: [...base.sharedInboxLocalParts],
    sharedInboxPrefixes: [...base.sharedInboxPrefixes],
    organizationLabelWords: [...base.organizationLabelWords],
    titleIndicatorTerms: [...base.titleIndicatorTerms],
    organizationFieldAliases: [...base.organizationFieldAliases],
    organizationNameSuffixes: [...base.organizationNameSuffixes],
  };

  const stringLists = [
    'headingTerms',
    'sharedInboxLocalParts',
    'sharedInboxPrefixes',
    'organizationLabelWords',
    'titleIndicatorTerms',
    'organizationFieldAliases',
    'organizationNameSuffixes',
  ] as const;

  for (const contribution of contributions) {
    for (const key of stringLists) {
      const extra = contribution[key];
      if (extra === undefined) continue;
      merged[key] = [...new Set([...merged[key], ...extra])];
    }
    if (contribution.urlHints !== undefined) {
      const byPattern = new Map(merged.urlHints.map((hint) => [hint.pattern, hint]));
      for (const hint of contribution.urlHints) {
        const existing = byPattern.get(hint.pattern);
        if (existing === undefined || hint.weight > existing.weight)
          byPattern.set(hint.pattern, hint);
      }
      merged.urlHints = [...byPattern.values()];
    }
  }

  return merged;
}
